version: '3.9'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    hostname: redis-master
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-replica1:
    image: redis:latest
    container_name: redis-replica1
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - redis-network

  redis-replica2:
    image: redis:latest
    container_name: redis-replica2
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    networks:
      - redis-network

  redis-sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    command: >
      redis-server /etc/redis/sentinel.conf --sentinel
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel1.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-network

  redis-sentinel2:
    image: redis:latest
    container_name: redis-sentinel2
    command: >
      redis-server /etc/redis/sentinel.conf --sentinel
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel2.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-network

  redis-sentinel3:
    image: redis:latest
    container_name: redis-sentinel3
    command: >
      redis-server /etc/redis/sentinel.conf --sentinel
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel3.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-network

  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis-sentinel1
      - redis-sentinel2
      - redis-sentinel3
    networks:
      - redis-network


networks:
  redis-network:
    driver: bridge
    external: true
    name: redis-cap_redis-network # remove if using docker